services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: kratos
    volumes:
      - mongo-data:/var/lib/postgresql/data
    ports:
      - 5432:5432