import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HomeSideBar from "@/components/home/sidebar/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Bak-Bak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(geistSans.variable, geistMono.variable, "font-sans")}>
        <div className="flex gap-3 bg-[#f9f8fc] px-3">
          <div className="w-full h-screen py-3 flex-none max-w-xs">
            <HomeSideBar />
          </div>
          <div className="flex-grow py-3  w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
